### Obtener todas las peliculas
GET http://localhost:4004/movies
Content-Type: application/json

### Obtener todas las peliculas con query params
GET http://localhost:4004/movies?page=2&limit=5&sort=DESC&genre=Drama&status=active
Content-Type: application/json

#### Obtener 1 película por ID
GET http://localhost:4004/movies/15
Content-Type: application/json

#### Crear una película
POST http://localhost:4004/movies
Content-Type: application/json

{
  "title": "The Exorcist",
  "genre": "Horror",
  "status": "active",
  "released": 1973,
  "directorId": 5
}

#### Editar una película
PUT http://localhost:4004/movies/19 
Content-Type: application/json

{
  "title": "Shaun of the Dead",
  "genre": "Horror|Comedy",
  "directorIds": [26]
}

#### Borrar
DELETE http://localhost:4004/movies/15
Content-Type: application/json

### Obtener todos los directores
GET http://localhost:4004/directors
Content-Type: application/json

#### Obtener 1 director por ID
GET http://localhost:4004/directors/5
Content-Type: application/json

#### Crear 1 director
POST http://localhost:4004/directors
Content-Type: application/json

{
  "name": "Christopher",
  "surname": "Nolan",
  "nationality": "British-American",
  "birthYear": 1970
}

#### Editar 1 director
PUT http://localhost:4004/directors/1
Content-Type: application/json

{
  "name": "Greta",
  "surname": "Gerwig",
  "nationality": "American",
  "birthYear": 1983
}

#### Borrar
DELETE http://localhost:4004/directors/12
Content-Type: application/json

### Obtener documentacion
GET http://localhost:4004/api-doc
Content-Type: application/json

